config/routes.rb
Rails.application.routes.draw do
  root 'shelters#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :shelters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shelter.rb
class Shelter <ApplicationRecord
  has_many :users
  validates :name, :slug, :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :address])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  before_action :authorize_user, except: [:index, :show]
  def index
    @shelters = Shelter.all.order(:name)
  end

  def show
    @shelter = Shelter.find(params[:id])
  end

  def new
    @shelter = Shelter.new
  end

  def create
    @shelter = Shelter.new(shelter_params)

    if @shelter.save
      flash[:notice] = "Shelter was saved successfully."
      redirect_to shelter_path(@shelter)
    else
      flash[:notice] = @shelter.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @shelter = Shelter.find(params[:id])
  end

  def update
    @shelter = Shelter.find(params[:id])
    if @shelter.update_attributes(shelter_params)
      flash[:notice] = "Shelter successfully updated."
      redirect_to shelter_path
    else
      flash[:notice] = "Error. Shelter not updated."
      render :edit
    end
  end

  protected

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "You do not have access to this page"
      redirect_to root_path
    end
  end

  def shelter_params
    params.require(:shelter).permit(:name, :slug, :address, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Shelter Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <%- if current_user -%>
        <li class="nav-item active">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <%- else -%>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, :class => 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, :class => 'nav-link'  %>
        </li>
        <%- end -%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShelterProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/nav_bar" %>
    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

    <%= yield %>

    <%= javascript_include_tag "application" %>

    <%= yield :extra_footer %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shelters/_form.html.erb
<%= form_for @shelter do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div><p>

  <div class="actions">
  <%= f.submit "Submit Shelter", :class => "form-buttons" %>
</div>
<% end %>

app/views/shelters/edit.html.erb
<%= 'Edit Shelter' %></br>
<%= render 'form' %>

app/views/shelters/index.html.erb
<div class="col-sm-8">
  <h2>Welcome to the Animal Shelter Project!</h2>
If you own a shelter or are a volunteer looking to sign up for hours, please sign in!<br>
Otherwise, please feel free to browse different animal shelters nationwide.<br><br>
</div>

<div class='shelters container'>
  Shelters:

  <ul><br />
    <% @shelters.each do |shelter| %>
      <p><%= link_to shelter.name, shelter_path(shelter) %>
    <% end %>
    </ul>

  <%= link_to 'New Shelter', new_shelter_path %>
</div>

app/views/shelters/new.html.erb
<div class='container'>
<div class='form'>
  <h2><%= 'New Shelter' %></h2>

  <%= render 'form', shelter: @shelter %><br />

  <%= link_to 'Back', shelters_path %>

</div>
</div>

app/views/shelters/show.html.erb
<%= @shelter.name %><br />
<%= @shelter.address %><br />
<%= @shelter.phone_number %><br />
<%= @shelter.email %><br /><br />

<%= link_to 'Edit Shelter', edit_shelter_path(@shelter) %>